### ISSUE TITLE
Potential Bug in FileServer.java

### ISSUE THREAD

**Issue by andronius-yang** [ucsd-cse15l-w23/skill-demo1-server#1]
Step 8 of the Skill Demonstration 1 says:

Demonstrate the server in a web browser using a query that returns just the file containing "Lucayans"

I am assuming that the expected output of this line is the file that was previously returned by the command line in step 6. However, the actual output given the path "/search?q=Lucayans" returns "No files found"

To recreate this symptom, I used the command line to find all files containing the common word "this" which returned 207 files. The server, given path "/search?q=this" returned "No files found"

While debugging, I believe the bug occurred at lines 51 to 55:

```
List<File> foundPaths = new ArrayList<>();
for(File f: paths) {
    if(f.toString().contains(parameters[1])) {
        foundPaths.add(f);
    }
}
```
Here, `f.toString()` was used to check if the file contains the string or not. However, according to java documentation, the `.toString()` function of a file returns the path as a string, not the actual contents. (https://docs.oracle.com/javase/7/docs/api/java/io/File.html)

To fix this bug, I changed `f.toString().contains(/*...*/)` to `FileHelpers.readFile().contains(/*...*/)` .

```
List<File> foundPaths = new ArrayList<>();
for(File f: paths) {
    if(FileHelpers.readFile(f).contains(parameters[1])) {
        foundPaths.add(f);
    }
}
```
Now the server works as intended. The path "/search?q=this" returns 207 files, and "/search?q=Lucayans" returns the designated file from step 6.

**Comment by jpolitz** [comment]
Thanks for asking. I've added a comment to FileServer.java to document that the current behavior is the expected behavior.
